# Server config
server:
  read_timeout: 4s
  write_timeout: 10s
  max_header_bytes: 1048576 # 1 MB
  time_for_graceful_shutdown: 10s # seconds
  read_header_timeout: 2s # seconds
  idle_timeout: 60s # seconds

# Logger config
logger:
  level: info
  format: text

# CORS policy
cors:
  allowed_origin: http://localhost:8080
  allow_credentials: true
  allowed_headers:
    - Content-Type
    - Content-Length
    - Authorization
    - X-API-Key
    - Accept
    - Origin
    - User-Agent
  allowed_methods:
    - GET
    - POST
  max_age: 24h

# Postgres config
postgres:
  max_open_conns: 25
  max_idle_conns: 25
  conn_max_lifetime: 5m # seconds, minutes
  conn_max_idle_lifetime: 2m # seconds, minutes

kafka:
  # Broker addresses
  bootstrap.servers: "localhost:9090"

  # --- Reliability & Delivery Guarantees ---
  # Wait for all in-sync replicas (ISR) to acknowledge. Prevents message loss.
  acks: "all"

  # Prevents duplicate messages and strictly guarantees ordering per partition.
  enable_idempotence: true

  # Infinite retries for transient network errors.
  retries: 2147483647

  # Max parallel requests. Value of 5 maintains order when idempotence is true.
  max_in_flight_requests_per.connection: 5

  # --- Latency & Batching ---
  # Time to wait (ms) to group messages. 5ms balances low latency and efficiency.
  linger_ms: 20

  # Maximum number of messages per batch.
  batch_num_messages: 1000

  # --- Compression ---
  # Compresses text efficiently with minimal CPU overhead.
  compression_type: "lz4"

  # --- Queue Management ---
  # Max messages allowed in the local producer queue buffer.
  queue_buffering_max_messages: 100000

  # Max time (ms) a message can spend in the queue before failing.
  message_timeout_ms: 30000

  # Number of partitions
  num_partitions: 1

  # Timeout for flush messages into broker (s)
  flash_timeout: 15

redis:
  dial_timeout: 1s
  read_timeout: 1s
  write_timeout: 1s
  chat_ttl: 24h

resolver:
  event_cap: 64

dispatch:
  send_cap: 64
  num_workers: 8

auth:
  jwks_url: "http://casdoor:8000/.well-known/jwks.json"
  allowed_signing_algorithms:
    - "RS256"
