// Code generated by MockGen. DO NOT EDIT.
// Source: resolver.go
//
// Generated by this command:
//
//	mockgen -source=resolver.go -destination=mocks/resolver_mocks.go -package=mock_resolver_repository
//

// Package mock_resolver_repository is a generated GoMock package.
package mock_resolver_repository

import (
	context "context"
	reflect "reflect"

	model "github.com/Evgen-Poloniy/chat-gateway/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockChannel is a mock of Channel interface.
type MockChannel struct {
	ctrl     *gomock.Controller
	recorder *MockChannelMockRecorder
	isgomock struct{}
}

// MockChannelMockRecorder is the mock recorder for MockChannel.
type MockChannelMockRecorder struct {
	mock *MockChannel
}

// NewMockChannel creates a new mock instance.
func NewMockChannel(ctrl *gomock.Controller) *MockChannel {
	mock := &MockChannel{ctrl: ctrl}
	mock.recorder = &MockChannelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannel) EXPECT() *MockChannelMockRecorder {
	return m.recorder
}

// ResolveEvent mocks base method.
func (m *MockChannel) ResolveEvent(ctx context.Context) (*model.EventMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveEvent", ctx)
	ret0, _ := ret[0].(*model.EventMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveEvent indicates an expected call of ResolveEvent.
func (mr *MockChannelMockRecorder) ResolveEvent(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveEvent", reflect.TypeOf((*MockChannel)(nil).ResolveEvent), ctx)
}

// SubscribeOnEventChannel mocks base method.
func (m *MockChannel) SubscribeOnEventChannel(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SubscribeOnEventChannel", ctx)
}

// SubscribeOnEventChannel indicates an expected call of SubscribeOnEventChannel.
func (mr *MockChannelMockRecorder) SubscribeOnEventChannel(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeOnEventChannel", reflect.TypeOf((*MockChannel)(nil).SubscribeOnEventChannel), ctx)
}

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
	isgomock struct{}
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// ExpireChatID mocks base method.
func (m *MockCache) ExpireChatID(ctx context.Context, chatID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireChatID", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExpireChatID indicates an expected call of ExpireChatID.
func (mr *MockCacheMockRecorder) ExpireChatID(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireChatID", reflect.TypeOf((*MockCache)(nil).ExpireChatID), ctx, chatID)
}

// GetChatMembers mocks base method.
func (m *MockCache) GetChatMembers(ctx context.Context, chatID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatMembers", ctx, chatID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatMembers indicates an expected call of GetChatMembers.
func (mr *MockCacheMockRecorder) GetChatMembers(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatMembers", reflect.TypeOf((*MockCache)(nil).GetChatMembers), ctx, chatID)
}
