// Code generated by MockGen. DO NOT EDIT.
// Source: messenger.go
//
// Generated by this command:
//
//	mockgen -source=messenger.go -destination=mocks/messenger_mocks.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	model "github.com/Evgen-Poloniy/chat-gateway/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMessengerRepository is a mock of MessengerRepository interface.
type MockMessengerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessengerRepositoryMockRecorder
	isgomock struct{}
}

// MockMessengerRepositoryMockRecorder is the mock recorder for MockMessengerRepository.
type MockMessengerRepositoryMockRecorder struct {
	mock *MockMessengerRepository
}

// NewMockMessengerRepository creates a new mock instance.
func NewMockMessengerRepository(ctrl *gomock.Controller) *MockMessengerRepository {
	mock := &MockMessengerRepository{ctrl: ctrl}
	mock.recorder = &MockMessengerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessengerRepository) EXPECT() *MockMessengerRepositoryMockRecorder {
	return m.recorder
}

// CreateDirectChat mocks base method.
func (m *MockMessengerRepository) CreateDirectChat(ctx context.Context, chat *model.DirectChat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDirectChat", ctx, chat)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDirectChat indicates an expected call of CreateDirectChat.
func (mr *MockMessengerRepositoryMockRecorder) CreateDirectChat(ctx, chat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDirectChat", reflect.TypeOf((*MockMessengerRepository)(nil).CreateDirectChat), ctx, chat)
}

// CreateGroupChat mocks base method.
func (m *MockMessengerRepository) CreateGroupChat(ctx context.Context, chat *model.GroupChat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroupChat", ctx, chat)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGroupChat indicates an expected call of CreateGroupChat.
func (mr *MockMessengerRepositoryMockRecorder) CreateGroupChat(ctx, chat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroupChat", reflect.TypeOf((*MockMessengerRepository)(nil).CreateGroupChat), ctx, chat)
}

// CreateUser mocks base method.
func (m *MockMessengerRepository) CreateUser(ctx context.Context, user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockMessengerRepositoryMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockMessengerRepository)(nil).CreateUser), ctx, user)
}

// GetChatsByUserID mocks base method.
func (m *MockMessengerRepository) GetChatsByUserID(ctx context.Context, userID int64, limit, offset int) ([]model.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatsByUserID", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]model.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatsByUserID indicates an expected call of GetChatsByUserID.
func (mr *MockMessengerRepositoryMockRecorder) GetChatsByUserID(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatsByUserID", reflect.TypeOf((*MockMessengerRepository)(nil).GetChatsByUserID), ctx, userID, limit, offset)
}

// GetUserDataByUserID mocks base method.
func (m *MockMessengerRepository) GetUserDataByUserID(ctx context.Context, userID int64) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserDataByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserDataByUserID indicates an expected call of GetUserDataByUserID.
func (mr *MockMessengerRepositoryMockRecorder) GetUserDataByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserDataByUserID", reflect.TypeOf((*MockMessengerRepository)(nil).GetUserDataByUserID), ctx, userID)
}

// GetUserDataByUsername mocks base method.
func (m *MockMessengerRepository) GetUserDataByUsername(ctx context.Context, username string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserDataByUsername", ctx, username)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserDataByUsername indicates an expected call of GetUserDataByUsername.
func (mr *MockMessengerRepositoryMockRecorder) GetUserDataByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserDataByUsername", reflect.TypeOf((*MockMessengerRepository)(nil).GetUserDataByUsername), ctx, username)
}

// UpdateChat mocks base method.
func (m *MockMessengerRepository) UpdateChat(ctx context.Context, chat *model.UpdateChat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChat", ctx, chat)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateChat indicates an expected call of UpdateChat.
func (mr *MockMessengerRepositoryMockRecorder) UpdateChat(ctx, chat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChat", reflect.TypeOf((*MockMessengerRepository)(nil).UpdateChat), ctx, chat)
}

// UpdateUser mocks base method.
func (m *MockMessengerRepository) UpdateUser(ctx context.Context, user *model.UpdateUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockMessengerRepositoryMockRecorder) UpdateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockMessengerRepository)(nil).UpdateUser), ctx, user)
}

// MockMessageBroker is a mock of MessageBroker interface.
type MockMessageBroker struct {
	ctrl     *gomock.Controller
	recorder *MockMessageBrokerMockRecorder
	isgomock struct{}
}

// MockMessageBrokerMockRecorder is the mock recorder for MockMessageBroker.
type MockMessageBrokerMockRecorder struct {
	mock *MockMessageBroker
}

// NewMockMessageBroker creates a new mock instance.
func NewMockMessageBroker(ctrl *gomock.Controller) *MockMessageBroker {
	mock := &MockMessageBroker{ctrl: ctrl}
	mock.recorder = &MockMessageBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageBroker) EXPECT() *MockMessageBrokerMockRecorder {
	return m.recorder
}

// SendMessage mocks base method.
func (m *MockMessageBroker) SendMessage(ctx context.Context, message *model.SendMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockMessageBrokerMockRecorder) SendMessage(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockMessageBroker)(nil).SendMessage), ctx, message)
}
